"""empty message

Revision ID: 08fae97047a7
Revises: c400ed1a1f7f
Create Date: 2023-10-24 20:59:38.267176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08fae97047a7'
down_revision = 'c400ed1a1f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_', sa.String(length=25), nullable=False))
        batch_op.add_column(sa.Column('password_', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('age_', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('phonenumber_', sa.Integer(), nullable=False))
        batch_op.drop_column('PhoneNumber')
        batch_op.drop_column('Password')
        batch_op.drop_column('Email')
        batch_op.drop_column('Name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Name', sa.VARCHAR(length=25), nullable=False))
        batch_op.add_column(sa.Column('Email', sa.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('Password', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('PhoneNumber', sa.INTEGER(), nullable=False))
        batch_op.drop_column('phonenumber_')
        batch_op.drop_column('age_')
        batch_op.drop_column('password_')
        batch_op.drop_column('name_')

    # ### end Alembic commands ###
