"""empty message

Revision ID: 8d4b5676b361
Revises: c2e861ae73e3
Create Date: 2023-10-24 20:08:16.685359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4b5676b361'
down_revision = 'c2e861ae73e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Mark', sa.String(length=25), nullable=False))
        batch_op.add_column(sa.Column('Model', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('Year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('Description', sa.String(length=500), nullable=False))
        batch_op.drop_column('email')
        batch_op.drop_column('name')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=25), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('Description')
        batch_op.drop_column('Year')
        batch_op.drop_column('Model')
        batch_op.drop_column('Mark')

    # ### end Alembic commands ###
